version: "3.9"

services:
  backend:
    build: ./backend
    container_name: fastapi-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./db.sqlite3:/app/db.sqlite3
    environment:
      - DATABASE_URL=sqlite:///./db.sqlite3

  frontend:
    build: ./frontend
    container_name: nextjs-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
